CREATE TABLE `customer`(
`id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
`name` VARCHAR(255) DEFAULT NULL,
`contact` VARCHAR(255) DEFAULT NULL COMMENT '联系人',
`telephone` VARCHAR(255) DEFAULT NULL,
`email` VARCHAR(255) DEFAULT NULL,
`remark` TEXT,
PRIMARY KEY (`id`)
)ENGINE=INNODB DEFAULT CHARSET=utf8;